#!/bin/bash
# emergency-rollback-master.sh - Master Emergency Rollback Script

set -euo pipefail

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

TIMESTAMP=$(date +%Y%m%d-%H%M%S)
LOG_FILE="emergency-rollback-$TIMESTAMP.log"

log() {
    echo -e "[$(date -Iseconds)] $1" | tee -a "$LOG_FILE"
}

success() {
    echo -e "${GREEN}✅ $1${NC}"
    log "SUCCESS: $1"
}

error() {
    echo -e "${RED}❌ $1${NC}"
    log "ERROR: $1"
}

warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
    log "WARNING: $1"
}

section() {
    echo -e "\n${BLUE}=== $1 ===${NC}"
    log "SECTION: $1"
}

section "EMERGENCY ROLLBACK INITIATED"
log "Starting emergency rollback procedures for Energy Drink Calculator App"
log "Timestamp: $TIMESTAMP"

# Create backup directory
BACKUP_DIR="emergency-backup-$TIMESTAMP"
mkdir -p "$BACKUP_DIR"

# Backup current state
log "Creating emergency backup..."
cp -r src/ "$BACKUP_DIR/" 2>/dev/null || true
cp -r .eslintrc.json next.config.ts package.json "$BACKUP_DIR/" 2>/dev/null || true

# Execute rollback phases
declare -A PHASE_STATUS

phases=(
    "emergency-isolation"
    "config-rollback"
    "dependency-recovery" 
    "code-quality-restoration"
    "runtime-recovery"
    "api-restoration"
    "data-validation"
    "performance-recovery"
    "security-recovery"
)

for phase in "${phases[@]}"; do
    section "Phase: $phase"
    if bash "rollback-$phase.sh"; then
        PHASE_STATUS[$phase]="SUCCESS"
        success "Phase completed: $phase"
    else
        PHASE_STATUS[$phase]="FAILED"
        error "Phase failed: $phase"
        warning "Continuing with next phase, manual intervention may be required"
    fi
done

# Generate rollback report
section "Generating Rollback Report"

cat > "rollback-report-$TIMESTAMP.md" << EOF
# Emergency Rollback Report

**Timestamp:** $TIMESTAMP  
**Status:** COMPLETED

## Rollback Phases Status
EOF

for phase in "${phases[@]}"; do
    status="${PHASE_STATUS[$phase]:-NOT_EXECUTED}"
    echo "- **$phase**: $status" >> "rollback-report-$TIMESTAMP.md"
done

cat >> "rollback-report-$TIMESTAMP.md" << EOF

## Post-Rollback Validation Results
- **TypeScript Compilation**: $(npx tsc --noEmit >/dev/null 2>&1 && echo "✅ PASS" || echo "❌ FAIL")
- **ESLint Validation**: $(npm run lint >/dev/null 2>&1 && echo "✅ PASS" || echo "❌ FAIL") 
- **API Health Check**: $(curl -f -s http://localhost:3000/api/health >/dev/null 2>&1 && echo "✅ PASS" || echo "❌ FAIL")
- **Build Verification**: $(npm run build >/dev/null 2>&1 && echo "✅ PASS" || echo "❌ FAIL")

## Emergency Backup Location
Emergency backup created at: $BACKUP_DIR/

## Next Steps
1. Monitor system stability for 24 hours
2. Investigate root cause of catastrophic failures
3. Implement preventive measures
4. Update validation procedures

---
*Generated by Emergency Rollback System v1.0*
EOF

# Final status
failed_phases=0
for phase in "${phases[@]}"; do
    if [[ "${PHASE_STATUS[$phase]:-}" == "FAILED" ]]; then
        ((failed_phases++))
    fi
done

if [ $failed_phases -eq 0 ]; then
    section "🎉 EMERGENCY ROLLBACK COMPLETED SUCCESSFULLY 🎉"
    success "All rollback phases completed successfully"
    success "System restored to last known stable state"
    success "Emergency backup available at: $BACKUP_DIR"
else
    section "⚠️ EMERGENCY ROLLBACK COMPLETED WITH ISSUES ⚠️"
    warning "$failed_phases phases failed - manual intervention may be required"
    error "Please review rollback report and backup directory"
fi

log "Rollback report generated: rollback-report-$TIMESTAMP.md"
log "Emergency rollback procedure completed"

exit 0